### ISSUE TITLE
Doesn't work as a pre-commit hook

### ISSUE THREAD

**Issue by fhorlaville** [Anadea/pre-commit-config-shellcheck#26]
Hi, when running it manually against the .pre-commit-config.yaml it works, but as a pre-commit hook it cannot find the file. Any suggestion? Is it because the file is git ignored? Many thanks

`$ git commit -m 'test'`
`pre-commit-config-shellcheck.........................(no files to check)Skipped`

**Comment by Artesius** [comment]
Hi!
Since you mentioned, that your pre-commit-config file is git ignored, I'm afraid it won't be checked with the pre-commit tool. This tool only operates on files which are in git, so running on things which are not in git is the opposite of what it is designed to do.

The way you can handle this problem is since pre-commit tracks even uncommited changes, you can add your files to the project, check them with pre-commit, and remove before commiting changes.
